apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: node-app
spec:
  containers:
    - name: node-app
      image: robinnagpal/kubernetes-tutorial-003-01-probes:latest
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /opt/probe_volume
          name: probe-volume
      livenessProbe:
        httpGet:
          port: 3000
          path: liveness
        initialDelaySeconds: 5
        failureThreshold: 2
        periodSeconds: 15
      startupProbe:
        httpGet:
          port: 3000
          path: startup
        initialDelaySeconds: 5
        failureThreshold: 2
        periodSeconds: 15
      readinessProbe:
        httpGet:
          port: 3000
          path: readiness
        initialDelaySeconds: 5
        failureThreshold: 2
        successThreshold: 2
        periodSeconds: 15

  volumes:
    - name: probe-volume
      hostPath:
        path: /probe_volume

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30464
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1
