apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: robinnagpal/kubernetes-tutorial-001-node-app:latest

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30464
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1
