version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
    - "8070:8080"
  nexus:
    image: sonatype/nexus3
    ports:
    - "8081:8081"
  sonarqube:
    image: sonarqube
    ports:
    - "9000:9000"
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
  splunk:
    image: splunk/splunk:latest
    ports:
    - "8000:8000"
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=<password>
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=tia
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:



## Wordpress and mariadb
```yaml
version: '2'

services:
  wordpress:
    image: wordpress:4.5
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - frontend
      - backend
    restart: always

  db:
    image: mariadb:10.1
    volumes:
      - "./volumes/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - frontend
      - backend
    

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge